management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

integrations:
  correios:
    calc-prazo-data: http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrazo